# Generated by Django 2.1.7 on 2019-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_auto_20190222_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
